export const cattleContent = {
  hero: {
    headline: "Best Cattle Management Software to Simplify Your Farm Operations",
    description: "Move past manual ledgers and WhatsApp groups. Hulm is the only platform in Pakistan specifically engineered for livestock traders and dairy farmers, unifying animal profiles, feed inventory, and FBR-compliant billing in one place.",
    primaryCTA: "Request Free Demo",
    secondaryCTA: "Talk to sales"
  },
  problems: {
    heading: "Are These Problems Holding Your Farm Back?",
    items: [
      {
        title: "Animal Identification & History",
        problem: "Trying to remember what you paid for a specific cow, its feed cost, and medical history when it's time to sell.",
        solution: "Every animal gets a digital profile. Track its exact purchase price, daily feed allocation cost, and medical history. When you sell, see the exact net profit generated by that specific animal.",
        solutionTitle: "The Hulm Fix: Digital Animal Profiles"
      },
      {
        title: "Hidden Feed & Farm Costs",
        problem: "You know total expenses, but have no idea if feed costs are eating your margins.",
        solution: "Track your grass, silage, wanda, and medicine. Set low-stock alerts before your farm runs out.",
        solutionTitle: "The Hulm Fix: Dedicated Inventory"
      },
      {
        title: "Financial Leakage in B2B Trading",
        problem: "Managing complex vendor payments, partial credits, or broker commissions natively.",
        solution: "Handle complex multi-party transactions instantly and issue professional, compliant invoices.",
        solutionTitle: "The Hulm Fix: Cattle-Specific Ledgers"
      }
    ]
  },
  features: {
    heading: "Complex Farm Operations, Simplified on One Screen",
    subheadline: "One powerful platform that replaces spreadsheets, paper records, and guesswork.",
    items: [
      {
        title: "Classify Your Herd",
        description: "Sort and track your stock by breed, milk production, weight, or age brackets. Generate reports on which livestock category yields the highest profit margin."
      },
      {
        title: "Never Miss a Dose",
        description: "Log illnesses and set automated reminders for vaccinations or vet visits. A healthy herd is a profitable herd, and Hulm ensures nothing slips through the cracks."
      },
      {
        title: "See the Real Numbers",
        description: "Stop guessing your margins. Hulm's Reporting & Analytics module pulls data from your feed purchases and animal sales to give you an exact, real-time Profit & Loss statement for your entire farm."
      }
    ]
  },
  compliance: {
    heading: "Transparent B2B Trading and Tax Compliance",
    description: "Hulm supports integrated tax and FBR compliance, allowing you to generate compliant invoices. Hulm does not hold FBR certification.",
    points: [
      {
        title: "Professional invoices for high-value herd sales",
        description: "Generate exact, professional invoices for high-value B2B herd sales."
      },
      {
        title: "Perfect digital records for every transaction",
        description: "Keep perfect digital records of every transaction for tax purposes."
      },
      {
        title: "FBR-compliant QR receipts, auto-generated",
        description: "Auto-generate FBR-compliant QR receipts when legally required."
      }
    ]
  }
};
