import type { IndustryData } from "./industriesData";

const trialCta = {
  primaryCtaText: "Start 14-Day Free Trial",
  primaryCtaLink: "https://app.hulmsolutions.com/Register",
  secondaryCtaText: "Book a Free Demo",
  secondaryCtaLink: "/book-a-demo/",
};

export const priorityIndustriesData: Record<string, IndustryData> = {
  "retail-store": {
    slug: "retail-store",
    name: "Retail Store",
    category: "Retail & Boutiques",
    image: "/images/industries/retail.jpg",
    cardTitle: "POS for Retail Stores",
    cardDesc: "Connect checkout, product stock, purchasing and customer records across your retail operation.",
    metaTitle: "Retail POS Software for Stores & Branches | Hulm",
    metaDescription: "Explore Hulm retail POS for barcode billing, inventory, product variants, customer records and multi-branch visibility.",
    hero: {
      badge: "Retail POS workflow",
      headline: "Keep checkout and retail stock working from the same view",
      description: "Hulm connects counter sales with products, purchasing, customer records and branch-level inventory so the team can serve customers without losing sight of stock.",
      ...trialCta,
    },
    overview: {
      heading: "A practical retail workflow from receiving to checkout",
      description: "Use one operating flow for the work around each sale: add products, receive stock, scan items, handle exchanges and review activity by branch.",
      points: ["Barcode and product catalogue workflows", "Size, colour and other product variants", "Customer and sales history", "Stock visibility across configured branches"],
    },
    problems: {
      heading: "Where the retail day usually slows down",
      items: [
        { problem: "Staff cannot quickly confirm whether the right item or variant is available.", solutionTitle: "Bring stock into the selling workflow", solution: "Keep product details and available variants accessible from the same system used at the counter." },
        { problem: "New stock, barcodes and purchase records live in separate tools or spreadsheets.", solutionTitle: "Connect receiving and product setup", solution: "Create products and organise incoming stock in the same platform used for sales and reporting." },
        { problem: "Returns and exchanges make stock records harder to trust.", solutionTitle: "Record the full transaction", solution: "Handle the exchange through the POS flow so the sale and resulting stock movement stay connected." },
      ],
    },
    features: {
      heading: "Retail capabilities to discuss for your setup",
      items: [
        { title: "Barcode billing", description: "Scan or select products and keep the sale connected to the product record." },
        { title: "Variant inventory", description: "Organise items by attributes such as size and colour where the catalogue requires it." },
        { title: "Purchasing and receiving", description: "Track supplier purchases and bring received stock into the inventory workflow." },
        { title: "Returns and exchanges", description: "Record product changes and payment differences through a consistent counter process." },
        { title: "Customer records", description: "Keep customer details and purchase history available for service and follow-up." },
        { title: "Branch reporting", description: "Review sales and stock activity by configured location and user access." },
      ],
    },
    useCases: { heading: "Common retail store POS setups", cases: [
      { title: "Independent shop", description: "Run daily billing, purchasing and stock from one store." },
      { title: "Multi-branch retailer", description: "Review sales and inventory across configured locations." },
      { title: "Variant-heavy catalogue", description: "Manage products that differ by size, colour or other attributes." },
    ] },
    whoCanBenefit: { heading: "Retail teams this workflow can support", items: ["General retail stores", "Supermarkets and convenience stores", "Fashion and footwear shops", "Electronics and speciality retailers"] },
    benefits: { heading: "What a connected retail workflow should improve", items: ["Fewer separate records around each sale", "Clearer product availability at the counter", "More consistent returns and exchanges", "A shared view of branch activity"] },
    fbr: {
      heading: "Connect retail invoicing with an FBR-ready rollout",
      description: "FBR integration is available for eligible Pakistan deployments. Confirm plan inclusion, registration requirements and implementation scope with Hulm.",
      points: [
        { title: "Connected invoice flow", description: "Keep the configured FBR invoice process close to the retail transaction." },
        { title: "Required invoice details", description: "Support the tax and invoice fields agreed during implementation." },
        { title: "Reviewable records", description: "Retain transaction activity for day-to-day review and reconciliation." },
      ],
    },
    faqs: [
      { question: "Can Hulm manage product variants?", answer: "Hulm can organise products using attributes such as size and colour. Confirm the exact catalogue structure and import approach during setup." },
      { question: "Can I use barcode scanners and receipt printers?", answer: "Yes. Hulm integrates easily with standard barcode scanners, receipt printers and cash drawers, so you can usually keep the hardware you already have." },
      { question: "Can multiple branches use the same system?", answer: "Multi-branch options are available. The right plan depends on the users, counters, locations and controls your operation needs." },
      { question: "Is FBR integration included?", answer: "FBR integration is available, but inclusion and implementation scope can vary by plan and business requirements. Confirm the final setup with Hulm." },
    ],
    finalCta: { heading: "Plan a retail POS around the way your store already works", subheading: "Bring your catalogue, branches and counter workflow to the conversation.", description: "Hulm can help map the suitable retail setup and rollout scope.", ...trialCta },
  },

  "restaurant-pos": {
    slug: "restaurant-pos",
    name: "Restaurant",
    category: "Food & Beverage",
    image: "/images/industries/restaurant.jpg",
    cardTitle: "POS for Restaurants",
    cardDesc: "Coordinate menus, orders, tables, billing and sales reporting in one restaurant workflow.",
    metaTitle: "Restaurant POS Software for Orders & Tables | Hulm",
    metaDescription: "Explore Hulm restaurant POS for menu management, order capture, tables, kitchen tickets and sales reporting.",
    hero: {
      badge: "Restaurant POS workflow",
      headline: "Move each order from the table or counter to billing with less friction",
      description: "Hulm brings menu items, order entry, table workflows, kitchen tickets and payment records into one operating flow for the restaurant team.",
      ...trialCta,
    },
    overview: {
      heading: "Keep front-of-house and fulfilment on the same order",
      description: "Give staff a shared path from order capture to preparation and payment, with a clearer record of what was sold during each shift.",
      points: ["Menu and modifier setup", "Counter and table order workflows", "Kitchen ticket routing options", "Shift and sales reporting"],
    },
    problems: { heading: "Where restaurant orders lose momentum", items: [
      { problem: "Order changes are passed verbally and can be missed between the floor and kitchen.", solutionTitle: "Keep changes attached to the order", solution: "Record items and configured modifiers before sending the order into the fulfilment workflow." },
      { problem: "Staff switch between separate tools for tables, bills and end-of-shift totals.", solutionTitle: "Use one restaurant flow", solution: "Connect table or counter orders with billing and daily sales records." },
      { problem: "Managers cannot easily compare what sold during a shift.", solutionTitle: "Review item and sales activity", solution: "Use shared reports to examine sales activity, popular items and operational patterns." },
    ] },
    features: { heading: "Restaurant capabilities to discuss for your setup", items: [
      { title: "Menu management", description: "Organise menu items, prices and available modifiers for order entry." },
      { title: "Table and counter orders", description: "Support the service model used by dine-in, takeaway or quick-service teams." },
      { title: "Kitchen tickets", description: "Route configured order details to the preparation workflow." },
      { title: "Bill handling", description: "Record payments and support the bill flows agreed during setup." },
      { title: "Ingredient visibility", description: "Connect selected menu sales to inventory workflows where configured." },
      { title: "Shift reporting", description: "Review sales activity by shift, user or configured location." },
    ] },
    useCases: { heading: "Common restaurant setups", cases: [
      { title: "Dine-in restaurant", description: "Coordinate tables, orders, kitchen communication and billing." },
      { title: "Quick-service counter", description: "Capture orders and move them quickly into fulfilment." },
      { title: "Multi-location operation", description: "Review configured menu and sales activity across branches." },
    ] },
    whoCanBenefit: { heading: "Food-service teams this workflow can support", items: ["Dine-in restaurants", "Quick-service restaurants", "Takeaway counters", "Small restaurant groups"] },
    benefits: { heading: "What a connected restaurant workflow should improve", items: ["Clearer handoff from order to preparation", "Fewer disconnected shift records", "More consistent menu and billing workflows", "Better visibility into sales activity"] },
    fbr: {
      heading: "Add FBR-connected invoicing to the restaurant workflow",
      description: "FBR integration is available for eligible Pakistan deployments. Hulm can confirm the appropriate configuration for your business and plan.",
      points: [
        { title: "Transaction-linked invoices", description: "Keep the configured invoice process connected to the completed restaurant sale." },
        { title: "Required invoice fields", description: "Support the tax and receipt details agreed during implementation." },
        { title: "Daily activity records", description: "Retain transaction information for review and reconciliation." },
      ],
    },
    faqs: [
      { question: "Can Hulm support dine-in and takeaway orders?", answer: "Hulm can support counter and table-based workflows. The team will confirm how dine-in, takeaway and other order types should be configured for your operation." },
      { question: "Does it support kitchen tickets?", answer: "Kitchen ticket workflows are available. Confirm the required stations, printers and order-routing rules before rollout." },
      { question: "Can I use it across restaurant branches?", answer: "Multi-branch options are available. Plan choice depends on the number of locations, users and management controls required." },
      { question: "Does restaurant inventory update automatically?", answer: "Inventory can be connected to the sales workflow where recipes or item rules are configured. The exact setup should be reviewed with Hulm." },
    ],
    finalCta: { heading: "Map your restaurant’s order flow before choosing the setup", subheading: "Bring your service model, stations and branch requirements.", description: "Hulm can help define the appropriate menu, order and reporting workflow.", ...trialCta },
  },

  "pharmacy-store": {
    slug: "pharmacy-store",
    name: "Pharmacy Store",
    category: "Healthcare & Services",
    image: "/images/industries/pharmacy.jpg",
    cardTitle: "POS for Pharmacies",
    cardDesc: "Connect counter billing with product, batch, expiry and purchasing records.",
    metaTitle: "Pharmacy POS Software for Stock & Billing | Hulm",
    metaDescription: "Explore Hulm pharmacy POS for counter billing, product batches, expiry visibility, purchasing and branch reporting.",
    hero: {
      badge: "Pharmacy POS workflow",
      headline: "Keep pharmacy billing close to batch and expiry information",
      description: "Hulm connects the counter with product records, purchasing, batches and expiry visibility so staff can sell while maintaining a clearer view of pharmacy stock.",
      ...trialCta,
    },
    overview: {
      heading: "A product-led workflow for the pharmacy counter",
      description: "Organise medicine and general retail items, receive purchases, review expiry information and record sales through one connected system.",
      points: ["Product, batch and expiry records", "Barcode counter billing", "Supplier purchases and receiving", "Branch-level sales and stock visibility"],
    },
    problems: { heading: "Where pharmacy stock becomes difficult to control", items: [
      { problem: "Expiry information sits outside the day-to-day stock record.", solutionTitle: "Keep expiry details with the product batch", solution: "Record batch and expiry information as part of the configured inventory workflow." },
      { problem: "Counter staff cannot quickly confirm available pack or product options.", solutionTitle: "Use a searchable product catalogue", solution: "Find configured products and pack information from the same system used for billing." },
      { problem: "Purchasing and sales records are reconciled manually.", solutionTitle: "Connect purchasing with inventory", solution: "Receive supplier purchases into the stock workflow used by the pharmacy counter." },
    ] },
    features: { heading: "Pharmacy capabilities to discuss for your setup", items: [
      { title: "Batch records", description: "Associate configured batch information with pharmacy inventory." },
      { title: "Expiry visibility", description: "Review recorded expiry dates to support stock rotation decisions." },
      { title: "Barcode billing", description: "Scan or select configured products during counter sales." },
      { title: "Pack and unit setup", description: "Define the product units and pack relationships your catalogue requires." },
      { title: "Supplier purchasing", description: "Record purchases and receive stock from configured vendors." },
      { title: "Branch reporting", description: "Review sales and stock activity across configured pharmacy locations." },
    ] },
    useCases: { heading: "Common pharmacy and medical store POS setups", cases: [
      { title: "Independent pharmacy", description: "Manage counter billing, purchasing and expiry-aware stock." },
      { title: "Pharmacy with general retail", description: "Keep medicine and non-medicine products in one catalogue." },
      { title: "Multi-branch pharmacy", description: "Review configured stock and sales activity by location." },
    ] },
    whoCanBenefit: { heading: "Pharmacy teams this workflow can support", items: ["Independent pharmacies", "Community medical stores", "Pharmacy chains", "Health and personal-care retailers"] },
    benefits: { heading: "What a connected pharmacy workflow should improve", items: ["Clearer batch and expiry records", "Faster access to product information", "More consistent purchasing records", "Shared visibility across configured branches"] },
    fbr: {
      heading: "Connect pharmacy invoices with the agreed FBR setup",
      description: "FBR integration is available for eligible Pakistan deployments. Tax treatment and implementation requirements should be confirmed for the pharmacy’s product mix.",
      points: [
        { title: "Configured invoice workflow", description: "Connect eligible sales with the FBR process agreed during implementation." },
        { title: "Product tax setup", description: "Apply the product and tax configuration confirmed for the deployment." },
        { title: "Transaction records", description: "Keep activity available for operational review and reconciliation." },
      ],
    },
    faqs: [
      { question: "Can Hulm track batches and expiry dates?", answer: "Hulm can store batch and expiry information within the configured inventory workflow. Confirm how existing data will be imported and maintained during setup." },
      { question: "Can products be sold by pack and unit?", answer: "Pack and unit relationships can be configured where required. Share representative products with Hulm so the right structure can be confirmed." },
      { question: "Does Hulm replace pharmacy or prescribing software?", answer: "This page describes POS and inventory workflows. Any clinical, prescribing or regulatory software requirement should be assessed separately before purchase." },
      { question: "Can several pharmacy branches use Hulm?", answer: "Multi-branch options are available. The appropriate plan depends on your locations, users and reporting needs." },
    ],
    finalCta: { heading: "Review your pharmacy catalogue and stock workflow with Hulm", subheading: "Bring sample products, pack structures and branch requirements.", description: "The team can help confirm the suitable POS and inventory setup.", ...trialCta },
  },

  "bakery-pos-system": {
    slug: "bakery-pos-system",
    name: "Bakery",
    category: "Food & Beverage",
    image: "/images/industries/bakery.jpg",
    cardTitle: "POS for Bakeries",
    cardDesc: "Connect counter sales, product availability and advance orders in one bakery workflow.",
    metaTitle: "Bakery POS Software for Counter & Advance Orders | Hulm",
    metaDescription: "Explore Hulm bakery POS for counter billing, batch and expiry visibility, advance orders, products and sales reporting.",
    hero: {
      badge: "Bakery POS workflow",
      headline: "Keep counter sales and advance bakery orders in one workflow",
      description: "Hulm connects daily billing with bakery products, availability, made-to-order work and sales records so the team can manage today’s counter and upcoming orders together.",
      ...trialCta,
    },
    overview: {
      heading: "A bakery workflow for what is ready now and what is due next",
      description: "Use one system to sell prepared items, record advance orders, organise products and review the sales activity behind each trading day.",
      points: ["Fast counter billing", "Advance and custom order records", "Batch and expiry visibility", "Product and sales reporting"],
    },
    problems: { heading: "Where bakery sales and fulfilment fall out of sync", items: [
      { problem: "Advance cake or catering orders are recorded away from the counter system.", solutionTitle: "Keep upcoming orders visible", solution: "Record the customer, due date and order details in the agreed bakery workflow." },
      { problem: "Staff cannot clearly see which products are available for sale.", solutionTitle: "Connect sales and product availability", solution: "Use the same product records for counter billing and configured stock visibility." },
      { problem: "Daily sales totals do not explain which products drove the result.", solutionTitle: "Review item-level activity", solution: "Use sales reporting to examine product performance and trading patterns." },
    ] },
    features: { heading: "Bakery capabilities to discuss for your setup", items: [
      { title: "Counter billing", description: "Sell prepared items using a focused product and payment workflow." },
      { title: "Advance orders", description: "Record configured order details, dates and customer information." },
      { title: "Product availability", description: "Keep the sellable product catalogue connected to stock records." },
      { title: "Batch and expiry records", description: "Record relevant production or receiving details for inventory review." },
      { title: "Customer history", description: "Keep customer and purchase records available for repeat service." },
      { title: "Sales reporting", description: "Review sales activity by product, user, day or configured branch." },
    ] },
    useCases: { heading: "Common bakery setups", cases: [
      { title: "Retail bakery", description: "Run prepared-product sales and daily stock from the counter." },
      { title: "Custom cake studio", description: "Record customer requirements and upcoming order dates." },
      { title: "Bakery with branches", description: "Review configured sales and product activity by location." },
    ] },
    whoCanBenefit: { heading: "Bakery teams this workflow can support", items: ["Neighbourhood bakeries", "Cake and dessert studios", "Bakery counters", "Multi-location bakery businesses"] },
    benefits: { heading: "What a connected bakery workflow should improve", items: ["Clearer visibility of upcoming orders", "Fewer separate counter and order records", "Better product-level sales visibility", "A consistent workflow across configured branches"] },
    fbr: {
      heading: "Add FBR-connected invoicing to the bakery counter",
      description: "FBR integration is available for eligible Pakistan deployments. Hulm can confirm the required invoice and product configuration for your rollout.",
      points: [
        { title: "Connected counter invoice", description: "Keep the agreed FBR process close to the completed bakery sale." },
        { title: "Configured product and tax details", description: "Use the invoice fields established during implementation." },
        { title: "Reviewable transaction history", description: "Retain sales activity for operational review and reconciliation." },
      ],
    },
    faqs: [
      { question: "Can Hulm record advance cake orders?", answer: "Advance order workflows can be configured to capture customer, date and order details. Confirm the information and fulfilment stages your team needs." },
      { question: "Can I track batches or expiry dates?", answer: "Batch and expiry information can be recorded where it is part of the configured inventory workflow." },
      { question: "Can the POS work for a bakery with a cafe?", answer: "Hulm can combine bakery counter and cafe-style workflows. The menu, order and stock structure should be mapped before rollout." },
      { question: "Can I compare bakery branches?", answer: "Multi-branch reporting options are available. The appropriate plan depends on your locations, users and reporting requirements." },
    ],
    finalCta: { heading: "Plan the bakery counter and advance-order flow together", subheading: "Bring your product list, order process and branch requirements.", description: "Hulm can help map the suitable POS and inventory setup.", ...trialCta },
  },

  "salon-pos": {
    slug: "salon-pos",
    name: "Salon / Spa",
    category: "Healthcare & Services",
    image: "/images/industries/salon.jpg",
    cardTitle: "POS for Salons and Spas",
    cardDesc: "Connect appointments, service billing, retail products and customer records at the front desk.",
    metaTitle: "Salon POS Software for Appointments & Billing | Hulm",
    metaDescription: "Explore Hulm salon POS for appointments, service billing, customer records, retail products and staff reporting.",
    hero: {
      badge: "Salon and spa POS workflow",
      headline: "Bring appointments, service billing and retail products to one front desk",
      description: "Hulm connects the salon calendar with services, customer records, product sales and reporting so reception and management share a clearer operating view.",
      ...trialCta,
    },
    overview: {
      heading: "A joined-up workflow from booking to payment",
      description: "Use one operating flow to organise appointments, bill services and products, maintain customer history and review salon activity.",
      points: ["Appointment and service records", "Service and retail product billing", "Customer visit history", "Staff and branch reporting options"],
    },
    problems: { heading: "Where the salon front desk gets fragmented", items: [
      { problem: "Appointments, customer notes and billing are maintained in separate places.", solutionTitle: "Connect the visit", solution: "Keep the configured booking, service and payment records in one workflow." },
      { problem: "Retail products sold during a visit are not reflected in stock records.", solutionTitle: "Bill products through the same POS", solution: "Connect product sales with the salon inventory record." },
      { problem: "Managers manually reconstruct staff and branch activity.", solutionTitle: "Use shared operational reporting", solution: "Review configured service, sales and user activity from one system." },
    ] },
    features: { heading: "Salon capabilities to discuss for your setup", items: [
      { title: "Appointment calendar", description: "Organise configured services, time slots and staff availability." },
      { title: "Service billing", description: "Add completed services and products to the customer bill." },
      { title: "Customer records", description: "Keep visit and purchase history available for ongoing service." },
      { title: "Retail inventory", description: "Track configured products sold from the salon or spa." },
      { title: "Staff activity", description: "Review service and sales activity using the rules established during setup." },
      { title: "Branch reporting", description: "Compare configured salon locations from a shared management view." },
    ] },
    useCases: { heading: "Common salon and spa setups", cases: [
      { title: "Independent salon", description: "Connect bookings, services, payments and product sales." },
      { title: "Salon with retail products", description: "Keep service and product transactions on the same customer record." },
      { title: "Multi-branch salon", description: "Review configured appointments and sales by location." },
    ] },
    whoCanBenefit: { heading: "Service teams this workflow can support", items: ["Hair and beauty salons", "Spas and wellness studios", "Barbershops", "Multi-location service businesses"] },
    benefits: { heading: "What connected salon software should improve", items: ["Fewer separate booking and billing records", "Clearer customer visit history", "Better visibility of retail product sales", "A shared view of staff and branch activity"] },
    faqs: [
      { question: "Can Hulm manage salon appointments?", answer: "Appointment workflows can be configured around services, staff and time slots. Confirm the scheduling rules your salon needs during setup." },
      { question: "Can services and retail products appear on one bill?", answer: "Hulm can combine configured services and products within the POS billing workflow." },
      { question: "Can I see customer visit history?", answer: "Customer records can retain visit and purchase activity captured through the system, subject to your setup and data practices." },
      { question: "Can several salon branches use Hulm?", answer: "Multi-branch options are available. The right plan depends on the number of locations, users and management controls required." },
    ],
    finalCta: { heading: "Map the salon visit from booking to payment", subheading: "Bring your services, staff structure and product list.", description: "Hulm can help confirm the right front-desk and reporting workflow.", ...trialCta },
  },

  "clothing-store": {
    slug: "clothing-store",
    name: "Clothing Store",
    category: "Retail & Boutiques",
    image: "/images/industries/clothing.jpg",
    cardTitle: "POS for Clothing Stores",
    cardDesc: "Manage sizes, colours, barcodes, exchanges and stock across fashion retail locations.",
    metaTitle: "Clothing Store POS for Variants & Inventory | Hulm",
    metaDescription: "Explore Hulm clothing store POS for size and colour variants, barcode billing, exchanges, purchasing and branch stock.",
    hero: {
      badge: "Fashion retail POS workflow",
      headline: "Keep every size, colour and sale connected to the right product",
      description: "Hulm brings variant-heavy product catalogues, barcode billing, exchanges, customer records and branch inventory into one clothing retail workflow.",
      ...trialCta,
    },
    overview: {
      heading: "A retail workflow built around product variants",
      description: "Organise each style and its variants, receive stock, sell at the counter, manage exchanges and review availability across configured locations.",
      points: ["Size and colour variant records", "Barcode and label workflows", "Returns and exchanges", "Branch-level stock visibility"],
    },
    problems: { heading: "Where fashion inventory becomes hard to trust", items: [
      { problem: "A style appears available, but the customer’s size or colour is not.", solutionTitle: "Track the product at variant level", solution: "Keep configured size and colour combinations attached to the correct item record." },
      { problem: "Exchanges are completed at the counter but corrected later in stock records.", solutionTitle: "Record exchanges as they happen", solution: "Use one transaction flow for the returned item, replacement item and payment difference." },
      { problem: "Staff cannot confirm whether another branch has the requested item.", solutionTitle: "Share branch-level visibility", solution: "Review configured location stock before deciding the next customer action." },
    ] },
    features: { heading: "Clothing retail capabilities to discuss for your setup", items: [
      { title: "Variant catalogue", description: "Organise styles by configured attributes such as size and colour." },
      { title: "Barcode billing", description: "Scan or select the correct product variant during checkout." },
      { title: "Labels and product setup", description: "Create and maintain the product information used by the counter team." },
      { title: "Exchanges and returns", description: "Record item changes and payment differences through the POS workflow." },
      { title: "Branch stock", description: "Review configured variant availability by retail location." },
      { title: "Customer history", description: "Keep captured purchase records available for service and follow-up." },
    ] },
    useCases: { heading: "Common clothing retail setups", cases: [
      { title: "Independent boutique", description: "Use Hulm as a boutique POS for a focused catalogue, counter sales and exchanges." },
      { title: "Multi-branch fashion retailer", description: "Review variant stock and sales across configured stores." },
      { title: "Mixed apparel catalogue", description: "Set up apparel POS records for products with different sizing and colour structures." },
    ] },
    whoCanBenefit: { heading: "Fashion retailers this workflow can support", items: ["Clothing boutiques", "Footwear retailers", "Uniform and workwear shops", "Multi-branch fashion stores"] },
    benefits: { heading: "What a connected clothing workflow should improve", items: ["Clearer variant availability", "More consistent exchanges and returns", "Faster access to branch stock information", "A shared view of product and customer activity"] },
    fbr: {
      heading: "Add FBR-connected invoicing to the clothing counter",
      description: "FBR integration is available for eligible Pakistan deployments. Confirm the product, tax and invoice configuration required for your rollout.",
      points: [
        { title: "Connected sales invoice", description: "Keep the agreed FBR process attached to the completed retail transaction." },
        { title: "Configured product details", description: "Use the invoice and tax fields established during implementation." },
        { title: "Reviewable sales history", description: "Retain transaction activity for operational review and reconciliation." },
      ],
    },
    faqs: [
      { question: "Can Hulm manage sizes and colours separately?", answer: "Hulm can organise products by configured attributes such as size and colour. The exact variant structure should be agreed before catalogue import." },
      { question: "Can staff check another branch’s stock?", answer: "Multi-branch stock visibility is available for configured locations and user permissions." },
      { question: "Can Hulm handle exchanges?", answer: "Exchange and return workflows are available. Confirm your approval rules, payment handling and stock process during setup." },
      { question: "Can I import my existing catalogue?", answer: "Data migration options are available. Hulm should review the current file structure, variants and data quality before confirming the migration scope." },
    ],
    finalCta: { heading: "Plan your clothing catalogue before moving the counter", subheading: "Bring sample styles, variants and branch requirements.", description: "Hulm can help confirm the right product, billing and stock structure.", ...trialCta },
  },
};
